HORNMOD_AddHorns({name = "sfx_401", info = "Ah! - Denis Brognard"},
{name = "sfx_402", info = "Dong - Taco Bell"},
{name = "sfx_403", info = "You! - Soulja Boy"},
{name = "sfx_404", info = "Jeanne! Au secours! - Jean-Marie LePen"},
{name = "sfx_405", info = "Kiyu"},
{name = "sfx_406", info = "Je suis un gamerz! - Laupok"},
{name = "sfx_407", info = "Bonjour - Tout sur les jeux"},
{name = "sfx_408", info = "WOW! - Eddy Wally"},
{name = "sfx_409", info = "Boy if you don't get"},
{name = "sfx_410", info = "Mais oui c'est clair! - Eddy Malou"},
{name = "sfx_411", info = "PAPA - Jean-Marie Bigard", extags = "papa"},
{name = "sfx_412", info = "Felicitations - Smash Bros 64", extags = "felicitations"},
{name = "sfx_413", info = "Coucou - miss jirachi", extags = "coucou"},
{name = "sfx_414", info = "WOAW - Johnny Crying", extags = "woaw"},
{name = "sfx_415", info = "Oh merde c'est con ca - Philippe Etchebest", extags = "c'est con ca"},
{name = "sfx_416", info = "C'etait vraiment tres interessant", extags = "interessant"},
{name = "sfx_417", info = "Caca dans des raviolis - Jean Pierre Coffe"},
{name = "sfx_418", info = "Aha - Mickey", extags = "aha"},
{name = "sfx_419", info = "Ne t'inquiete pas ca va bien se passer", extags = "yoda"},
{name = "sfx_420", info = "C'etait sur - Sardoche", extags = "Sardoche"},
{name = "sfx_421", info = "Non. - Hotel Mario", extags = "non"},
{name = "sfx_422", info = "Coucou, tu veux voir ma bite ?", extags = "Bite"},
{name = "sfx_423", info = "Euh nique ta mere - Marine LePen", extags = "Marine LePen"},
{name = "sfx_424", info = "Ta Gueule - TheFantasio974", extags = "Fanta"},
{name = "sfx_425", info = "Ouais mais c'est pas toi qui decides - TheFantasio974", extags = "Fanta"},
{name = "sfx_426", info = "Cliquez bande de salopes - Morsay", extags = "morsay"},
{name = "sfx_427", info = "Clique salope - Morsay", extags = "morsay"},
{name = "sfx_428", info = "El Risitas - Issou", extags = "issou"},
{name = "sfx_429", info = "Viens ici sale encule - Hitman the Cobra", extags = "viens ici"},
{name = "sfx_430", info = "Mario - Smash Bros 64", extags = "mario"},
{name = "sfx_431", info = "J'en ai rien a foutre - Siphano", extags = "siphano"},
{name = "sfx_432", info = "Leo Tech Maker", extags = "leo"},
{name = "sfx_433", info = "C'est normal en Russie! - Antoine Daniel"},
{name = "sfx_434", info = "REEEEEEEEEE"},
{name = "sfx_435", info = "Oui - Didier Drogba", extags = "Oui"},
{name = "sfx_436", info = "La boule magique - M6 Boutique", extags = "boule magique"},
{name = "sfx_437", info = "Ta gueule - Hitman the Cobra", extags = "Ta gueule"},
{name = "sfx_438", info = "Ta gueule - 2 minutes du peuple", extags = "francois"},
{name = "sfx_439", info = "Waouh qu'est ce que c'est ce truc la - Sylvain Durif", extags = "sylvain durif"},
{name = "sfx_440", info = "C'est pas gentil d'être méchant - Paulok"},
{name = "sfx_441", info = "Bande de gros FDP - Paulok"},
{name = "sfx_442", info = "Peppa Pig - Paulok"},
{name = "sfx_443", info = "PUTAIN - Paulok"},
{name = "sfx_444", info = "AAAA AAAA AAAAAA - Paulok"},
{name = "sfx_445", info = "NAN! - Laupok"},
{name = "sfx_446", info = "J'suis a poil - Securite routiere", extags = "a poil"},
{name = "sfx_447", info = "Ui - Les pubs locales misterjday", extags = "ui"},
{name = "sfx_448", info = "C'est honteux", extags = "c'est honteux"},
{name = "sfx_449", info = "Ca fait beaucoup la non - Mister V", extags = "ca fait beaucoup"},
{name = "sfx_450", info = "Je chiale PUTAIN - Antoine Daniel", extags = "Antoine Daniel"},
{name = "sfx_451", info = "Horn 1 - TrackMania", extags = "tm"},
{name = "sfx_452", info = "Horn 2 - TrackMania", extags = "tm"},
{name = "sfx_453", info = "Horn 3 - TrackMania", extags = "tm"},
{name = "sfx_454", info = "Horn 4 - TrackMania", extags = "tm"})
